# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-GB"
title: "Luke Leigh's Blog"
title_separator: "|"
subtitle: "Yet another IT Admin Blog"
name: "Luke Leigh"
description: "Blogsite for sharing articles on PowerShell and other IT related posts"
url: "https://blog.lukeleigh.com"
repository: "BanterBoy/BanterBoy.github.io"
logo: "/assets/images/PowerShell_5.0_icon88x88.png"
twitter_username: luke_leighs
github_username: BanterBoy
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.17.2
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: GB # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Analytics
analytics:
  provider: "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: "G-4TQHPE7E2J"
    anonymize_ip: # true, false (default)

include:
  - _pages
  - _docs

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name: "Luke Leigh"
  avatar: "/assets/images/bio-photo.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "PowerShell / Infrastructure Engineer"
  location: "Essex, UK"
  email: "me@lukeleigh.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
    - label: "Profile"
      icon: "fas fa-fw fa-link"
      url: "https://velocv.com/lukeleigh"
    - label: "adminTookit"
      icon: "fas fa-hashtag"
      url: "https://admintoolkit.lukeleigh.com"
    - label: "PSCiscoMeraki"
      icon: "fas fa-hashtag"
      url: "https://psciscomeraki.lukeleigh.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/luke_leighs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BanterBoy"
    - label: "keybase"
      icon: "fab fa-fw fa-keybase"
      url: "https://keybase.io/lukeleigh"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
    - label: "Profile"
      icon: "fas fa-fw fa-link"
      url: "https://velocv.com/lukeleigh"
    - label: "adminTookit"
      icon: "fas fa-hashtag"
      url: "https://admintoolkit.lukeleigh.com"
    - label: "PSCiscoMeraki"
      icon: "fas fa-hashtag"
      url: "https://psciscomeraki.lukeleigh.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/luke_leighs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BanterBoy"
    - label: "keybase"
      icon: "fab fa-fw fa-keybase"
      url: "https://keybase.io/lukeleigh"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _docs
  - scope:
    path: "_docs"
    type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
