# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-GB"
title: "Luke Leigh's Blog"
title_separator: "-"
subtitle: "Yet another IT Admin Blog"
name: "Luke Leigh"
description: "Blogsite for sharing articles on PowerShell and other IT related posts"
url: "https://blog.lukeleigh.com"
repository: "BanterBoy/BanterBoy.github.io"
logo: "/assets/images/PowerShell_5.0_icon88x88.png"
words_per_minute: 220
twitter_username: luke_leighs
github_username: BanterBoy
minimal_mistakes_skin: dark
teaser: /assets/images/default-teaser-image.png
breadcrumbs: true # disabled by default
github: [metadata]

# Search Settings
search: true
search_provider: algolia
algolia:
  application_id: # LOEP7YNBRV
  index_name: # blogindex
  search_only_api_key: # 1514f1706e03817a804733810ebcc7ea
  powered_by: # true (default), false

# Comments
# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "lukeleigh"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.17.2

# Analytics
analytics:
  provider: "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: "G-PK0X4FK6KJ"
    anonymize_ip: false # true, false (default)

# Reading Files
include:
  - _pages
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
  # - Gemfile
  # - Gemfile.lock
  # - node_modules
  # - "vendor/bundle/"
  # - "vendor/cache/"
  # - "vendor/gems/"
  # - "vendor/ruby/"
exclude: [vendor]

# Site Author
author:
  name: "Luke Leigh"
  avatar: "/assets/images/bio-photo.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "PowerShell Developer / <br>Infrastructure Engineer"
  location: "Essex, UK"
  email: "me@lukeleigh.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
    - label: "Profile"
      icon: "fas fa-fw fa-link"
      url: "https://velocv.com/lukeleigh"
    - label: "adminToolkit"
      icon: "fas fa-fw fa-external-link-alt"
      url: "https://admintoolkit.lukeleigh.com"
    - label: "PSCiscoMeraki"
      icon: "fas fa-fw fa-external-link-alt"
      url: "https://psciscomeraki.lukeleigh.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/luke_leighs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BanterBoy"
    - label: "keybase"
      icon: "fab fa-fw fa-keybase"
      url: "https://keybase.io/lukeleigh"

footer:
  links:
    - label: "Profile"
      icon: "fas fa-fw fa-link"
      url: "https://velocv.com/lukeleigh"
    - label: "adminToolkit"
      icon: "fas fa-fw fa-external-link-alt"
      url: "https://admintoolkit.lukeleigh.com"
    - label: "PSCiscoMeraki"
      icon: "fas fa-fw fa-external-link-alt"
      url: "https://psciscomeraki.lukeleigh.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/luke_leighs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BanterBoy"
    - label: "keybase"
      icon: "fab fa-fw fa-keybase"
      url: "https://keybase.io/lukeleigh"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: GB # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
